# Generated by Django 5.1.1 on 2024-09-08 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_who', models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Post Kategoriyalari',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, default=1, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbmodels.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tbmodels.users')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'db_table': 'post',
            },
        ),
    ]
