# Generated by Django 5.0.8 on 2024-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('telegramid', models.BigIntegerField(blank=True, default=1, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
