# Generated by Django 5.1.1 on 2024-09-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='for_who',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=20, verbose_name='KIM UCHUN'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='KATEGORIYA NOMI'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbmodels.category', verbose_name='CATEGORIYA NOMI'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='YARATILGAN VAQT'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RASM'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='TEXT'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tbmodels.users', verbose_name='POST/MUROJAAT EGASI'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='VIDEO'),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='TELEFON RAQAM'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, default=1, null=True, unique=True, verbose_name='TELEGRAM ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='USERNAME'),
        ),
    ]
