# Generated by Django 5.0.8 on 2024-08-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0002_users_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='telegramid',
            new_name='telegram_id',
        ),
    ]
