# Generated by Django 5.0.8 on 2024-08-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0004_category_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_who',
            field=models.CharField(choices=[('adults', 'Adults'), ('children', 'Children')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
