# Generated by Django 5.0.8 on 2024-08-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0005_category_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='for_who',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=20),
        ),
    ]
