# Generated by Django 5.0.8 on 2024-08-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0007_alter_category_name_alter_posts_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='updated_time',
        ),
    ]
