# Generated by Django 5.0.8 on 2024-08-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0008_remove_posts_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
