# Generated by Django 5.0.8 on 2024-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0009_alter_posts_image_alter_posts_text_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
