# Generated by Django 5.0.8 on 2024-08-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0011_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tbmodels.users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
