# Generated by Django 5.0.8 on 2024-08-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbmodels', '0012_alter_posts_image_alter_posts_text_alter_posts_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Post Kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
