# Generated by Django 5.1.1 on 2024-09-08 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tbmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('for_who', models.CharField(choices=[('workers', 'workers'), ('specialists', 'specialists')], max_length=20)),
                ('count_questions', models.IntegerField()),
                ('picture', models.CharField(max_length=500)),
                ('time_limit', models.DurationField(null=True)),
                ('red_line', models.IntegerField()),
                ('answers', models.CharField(max_length=221)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_true', models.IntegerField(blank=True, null=True)),
                ('counts_false', models.IntegerField(blank=True, null=True)),
                ('time_duration', models.DurationField(blank=True, null=True)),
                ('is_successful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbmodels.users')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.tests')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Natijalar',
                'db_table': 'result',
            },
        ),
    ]
