# Generated by Django 5.0.8 on 2024-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='red_line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
