# Generated by Django 5.0.8 on 2024-09-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_alter_results_created_at_alter_tests_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='answers',
            field=models.CharField(max_length=221),
        ),
    ]
